// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using LiveChartsCore.Kernel;
using LiveChartsCore;
using LiveChartsCore.SkiaSharpView.Drawing;
using System.Drawing;
using LiveChartsCore.SkiaSharpView;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using LiveChartsCore.Measure;
using LiveChartsCore.Drawing;

namespace StockDesktopWidget.UI.Widgets.AppleMac
{
    [Register("CartesianChart")]
    public partial class CartesianChart : NSView, ICartesianChartView<SkiaSharpDrawingContext>
    {
        private CollectionDeepObserver<ISeries> seriesObserver;
        private CollectionDeepObserver<IAxis> xObserver;
        private CollectionDeepObserver<IAxis> yObserver;
        protected Chart<SkiaSharpDrawingContext> core;
        //protected MotionCanvas motionCanvas;
        protected IChartLegend<SkiaSharpDrawingContext> legend;
        protected IChartTooltip<SkiaSharpDrawingContext> tooltip;
        private ActionThrottler mouseMoveThrottler;
        private PointF mousePosition = new PointF();
        private nfloat currentScaleFactor = 1;

        private MotionCanvas canvas;

        private IEnumerable<ISeries> _series = new ObservableCollection<ISeries>();
        private IEnumerable<IAxis> _xAxis = new List<IAxis>();
        private IEnumerable<IAxis> _yAxis = new List<IAxis>();

        public CartesianChart(IntPtr handle) : base(handle)
        {
            currentScaleFactor = NSScreen.MainScreen.BackingScaleFactor;
        }

        public IEnumerable<IAxis> XAxes
        {
            get => _xAxis;
            set
            {
                xObserver.Dispose(_xAxis);
                _xAxis = value;
                xObserver.Initialize(value);
                if (core is null)
                {
                    return;
                }

                BeginInvokeOnMainThread(() => core.Update());
            }
        }

        public override bool MouseDownCanMoveWindow => true;

        public IEnumerable<IAxis> YAxes
        {
            get => _yAxis;
            set
            {
                yObserver.Dispose(_yAxis);
                _yAxis = value;
                yObserver.Initialize(value);
                if (core is null)
                {
                    return;
                }

                BeginInvokeOnMainThread(() => core.Update());
            }
        }
        public IEnumerable<ISeries> Series
        {
            get => _series;
            set
            {

                seriesObserver.Dispose(_series);
                _series = value;
                seriesObserver.Initialize(value);
                if (core is null)
                {
                    return;
                }

                BeginInvokeOnMainThread(() => core.Update());
            }
        }

        public ZoomMode ZoomMode { get; set; }

        public double ZoomingSpeed { get; set; } = 0.5;

        public CartesianChart<SkiaSharpDrawingContext> Core => (CartesianChart<SkiaSharpDrawingContext>)core;


        public MotionCanvas<SkiaSharpDrawingContext> CoreCanvas => canvas.CanvasCore;

        public IChartLegend<SkiaSharpDrawingContext> Legend { get; }

        public IChartTooltip<SkiaSharpDrawingContext> Tooltip { get; }

        public PointStatesDictionary<SkiaSharpDrawingContext> PointStates { get; set; }

        public SizeF ControlSize
        {
            get
            {
                return new SizeF
                {
                    Height = (float)(Bounds.Height * currentScaleFactor),
                    Width = (float)(Bounds.Width * currentScaleFactor)
                };
            }
        }

        public Margin DrawMargin { get; set; }
        public TimeSpan AnimationsSpeed { get; set; } = TimeSpan.FromMilliseconds(500);
        public Func<float, float> EasingFunction { get; set; } = EasingFunctions.SinOut;
        public LegendPosition LegendPosition { get; set; } = LegendPosition.Hidden;
        public LegendOrientation LegendOrientation { get; set; } = LegendOrientation.Auto;
        public TooltipPosition TooltipPosition { get; set; } = TooltipPosition.Hidden;
        public TooltipFindingStrategy TooltipFindingStrategy { get; set; } = TooltipFindingStrategy.CompareOnlyX;


        public void Initialize(MotionCanvas canvas)
        {
            this.canvas = canvas;
            if (!LiveCharts.IsConfigured) LiveCharts.Configure(LiveChartsSkiaSharp.DefaultPlatformBuilder);

            var stylesBuilder = LiveCharts.CurrentSettings.GetStylesBuilder<SkiaSharpDrawingContext>();
            var initializer = stylesBuilder.GetInitializer();
            if (stylesBuilder.CurrentColors == null || stylesBuilder.CurrentColors.Length == 0)
                throw new Exception("Default colors are not valid");
            initializer.ConstructChart(this);
            InitializeCore();

            var x = new NSNotificationCenter();
            x.AddObserver(new NSString("NSViewBoundsDidChangeNotification"), OnSizeChanged);

            //mouseMoveThrottler = new ActionThrottler(MouseMoveThrottlerUnlocked, TimeSpan.FromMilliseconds(10));

            seriesObserver = new CollectionDeepObserver<ISeries>(OnDeepCollectionChanged, OnDeepCollectionPropertyChanged, true);
            xObserver = new CollectionDeepObserver<IAxis>(OnDeepCollectionChanged, OnDeepCollectionPropertyChanged, true);
            yObserver = new CollectionDeepObserver<IAxis>(OnDeepCollectionChanged, OnDeepCollectionPropertyChanged, true);

            XAxes = new List<IAxis>() { new Axis() };
            YAxes = new List<IAxis>() { new Axis() };
            Series = new ObservableCollection<ISeries>();
        }

        protected void InitializeCore()
        {
            //if (!(FindByName("canvas") is MotionCanvas canvas))
            //    throw new Exception(
            //        $"SkiaElement not found. This was probably caused because the control {nameof(CartesianChart)} template was overridden, " +
            //        $"If you override the template please add an {nameof(MotionCanvas)} to the template and name it 'canvas'");

            core = new CartesianChart<SkiaSharpDrawingContext>(this, LiveChartsSkiaSharp.DefaultPlatformBuilder, canvas.CanvasCore);
            //legend = Template.FindName("legend", this) as IChartLegend<SkiaSharpDrawingContext>;
            //tooltip = Template.FindName("tooltip", this) as IChartTooltip<SkiaSharpDrawingContext>;
            BeginInvokeOnMainThread(() => core.Update());
        }

        private void OnSizeChanged(NSNotification notification)
        {

        }


        private void OnDeepCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            InvokeOnMainThread(() => core.Update());

        }

        private void OnDeepCollectionPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            InvokeOnMainThread(() => core.Update());
        }

        public PointF ScaleUIPoint(PointF point, int xAxisIndex = 0, int yAxisIndex = 0)
        {
            return Core.ScaleUIPoint(point, xAxisIndex, yAxisIndex);
        }
    }
}
