// The MIT License(MIT)
//
// Copyright(c) 2021 Alberto Rodriguez Orozco & LiveCharts Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using System.Text;
using LiveChartsGenerators.Definitions;
using LiveChartsGenerators.Frameworks;
using Microsoft.CodeAnalysis;

namespace LiveChartsGenerators.Templates;

public static class BindablePropertyTempaltes
{
    public static string GetTemplate(XamlProperty target, FrameworkTemplate template)
    {
        var propertyName = target.Name;

        var type = target.DeclaringType;

        var displayFormat = new SymbolDisplayFormat(
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameOnly,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters);

        var declaringType = type.ToDisplayString(displayFormat);

        var displayFormat2 = new SymbolDisplayFormat(
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters);

        var propertyType = $"global::{target.Type.ToDisplayString(displayFormat2)}";

        var sanitizedPropertyType = target.Type.IsReferenceType && propertyType.EndsWith("?")
            ? propertyType.Substring(0, propertyType.Length - 1)
            : propertyType;

        return @$"// <auto-generated>
//     This code was generated by a LiveCharts source generator, do not edit.
// </auto-generated>

{target.Headers}

namespace {type.ContainingNamespace};

{GetFormattedAccessibility(type.DeclaredAccessibility)} partial class {declaringType}
{{
    /// <summary>
    ///    The <see cref=""{propertyName}""/> property for xaml.
    /// </summary>
    {template.DeclareBindableProperty(propertyName, sanitizedPropertyType)} =
        {template.CreateBindableProperty(propertyName, sanitizedPropertyType, declaringType, target.DefaultValueExpression ?? "null", target.OnChangedExpression)}

    /// <summary>
    ///    Gets or sets the <see cref=""{propertyName}""/> property.
    /// </summary>
    public {propertyType} {propertyName}
    {{
        get => ({propertyType})GetValue({propertyName}Property);
        set => SetValue({propertyName}Property, value);
    }}
}}";
    }

    public static string GetAvaloniaBaseTypeTemplate(IGrouping<ISymbol?, XamlProperty?> group, FrameworkTemplate template)
    {
        var baseTypeSymbol = group.Key!; // ! not nullable at this point.

        var sb = new StringBuilder();

        foreach (var item in group)
        {
            if (item is not { } value) continue;
            if (value.OnChangedExpression is null) continue;

            _ = sb.AppendLine($"        [\"{value.Name}\"] = {value.OnChangedExpression},");
        }

        return @$"// <auto-generated>
//     This code was generated by a LiveCharts source generator, do not edit.
// </auto-generated>

using System.Collections.Generic;

namespace {baseTypeSymbol.ContainingNamespace};

{GetFormattedAccessibility(baseTypeSymbol.DeclaredAccessibility)} partial class {baseTypeSymbol.Name}
{{
    private readonly Dictionary<string, System.Action<global::Avalonia.AvaloniaPropertyChangedEventArgs>> _changes = new()
    {{
{sb}
    }};

    /// <summary>
    /// Called when a property value changes.
    /// </summary>
    /// <param name=""change"">The change.</param>
    protected override void OnPropertyChanged(global::Avalonia.AvaloniaPropertyChangedEventArgs change)
    {{
        base.OnPropertyChanged(change);
        OnXamlObjectPropertyChanged(change); // define this method if needed.
        if (_changes.TryGetValue(change.Property.Name, out var action)) action(change);
    }}

    partial void OnXamlObjectPropertyChanged(global::Avalonia.AvaloniaPropertyChangedEventArgs change);
}}
";
    }

    private static string GetFormattedAccessibility(Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Private => "private",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "protected internal",
            Accessibility.ProtectedOrInternal => "private protected",
            Accessibility.NotApplicable => "not applicable",
            _ => "unknown"
        };
    }
}
