  
name: Publish Avalonia

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: dotnet build  ./src/skiasharp/LiveChartsCore.SkiaSharp.Avalonia --configuration Release
          
    # - name: Publish LiveChartsCore.SkiaSharpView.Avalonia
    #   uses: brandedoutcast/publish-nuget@v2.5.5
    #   with:
    #       PROJECT_FILE_PATH: src/skiasharp/LiveChartsCore.SkiaSharp.Avalonia/LiveChartsCore.SkiaSharpView.Avalonia.csproj
    #       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    #       NUGET_SOURCE: https://api.nuget.org
    #       INCLUDE_SYMBOLS: true
